<style type="text/css">
.bigTitle{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#234567;font-size:18px;text-decoration:none;}

.enterTitle1{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#3B6077;font-size:50pt;text-decoration:none;}
.enterTitle2{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#3B6077;font-size:40pt;text-decoration:none;}
.enterTitle3{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#3B6077;font-size:35pt;text-decoration:none;font-weight:bold;}
.enterTitle4{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#3B6077;font-size:30pt;text-decoration:none;}

.menuTitle{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#234567;font-size:18px;text-decoration:underline;}
.normalTitle{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#234567;font-size:14px;}
.smallTitle{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';color:#234567;font-size:12px;}
.recordTitle{font-family: ' arial (hebrew) ,web hebrew ad, Courier New (Hebrew)';;font-size:16px;}

.subtleText {
	color: #A0A0B0;
	font: 8pt Arial;
}

body {
  background-color: #B2D3F0;
}

.dataTable {
	font: 10pt Tahoma;
	color: #000000;
	background: #FFFFFF;
	border: 1px solid #949494;
}

.dataTable caption {
	font: 13pt Tahoma;
	letter-spacing: 0.2em;
	padding: 0.5em;
	background: transparent;
}

.dataTable thead th {
	background: #D12C26;
	color: #FFFFFF;
	padding: 1em 0.7em 1em 0.7em;
	font: 10pt "Tahoma";
	font-weight: bold;
}

.dataTable tbody td, tbody th {
	padding: 0.5em;
}

.dataTable tbody tr.odd {
	background: #E9E9E9;
}

.dataTable tbody tr {
	background: #D1E8FF;
}

.dataTable tfoot td, tfoot th {
	background: #D12C26;
	color: #FFFFFF;
	padding: 0.5em 0.7em 0.5em 0.7em;
	font: 10pt "Tahoma";
	font-weight: bold;
}

.dataTable tbody a {
	font-weight: bold;
	text-decoration: underline;
	color: #000000;
}

.dataTable tbody a:hover {
	text-decoration: underline;
}

.dataTable tbody a:visited {
	color: #474747;
}

</style>

